#' Generates trace plots to examine chain convergence
#'
#' This function generates trace plots for a indicated parameter to monitor chain convergence in the MCMC inversion.
#' If the parameter is time-dependent, multiple plots can be generated by increasing 'n' argument - the function will
#' randomly select the time step to display. Dependencies: 'mcmcplots'.
#'
#' @param inv_out User inputs the MCMC data object that is returned by the 'run_inversion' function. Defaults to 'inv_out'.
#'
#' @param parm Specify which parameter to plot. This parameter must be included in 'save.parms' argument in 'run_inversion'
#' function. Defaults to 'pco2'.
#'
#' @param n Indicate the number of plots to step through if parameter is time-dependent. Defaults to '1'.
#'
#' @returns Returns trace plot(s) to user's plot window.
#'
#' @examples
#' trace_plot(inv_out = inv_out, parm = "pco2", n = 1)
#'
#' @export
trace_plot <- function(inv_out = inv_out, 
                       parm = "pco2", 
                       n = 3){

  if(length(inv_out) != 4){
    stop("'inv_out' must be a list containing 3 elements from 'run_inversion' function")
  }

  jout <- inv_out[[1]]
  ages_prox <- inv_out[[2]]
  save.parms <- inv_out[[3]]

  # stop if parm is not time-dependent or it is not in the save.parm list
  if(!(parm %in% save.parms)){
    stop("Must input a parameter (i.e., 'parm' argument) that is in the 'save.parms' list used as argument for 'inv_out' function")
  }

  mcmcplots::traplot(jout, parms = parm, random = TRUE)

  if(n > 1){
    i = 2
    repeat{
      mcmcplots::traplot(jout, parms = parm, random = TRUE)
      if(i > n-1){
        break
      }
      i = i + 1
    }
  }
  return()
}
